# Generated by Django 4.2.7 on 2023-11-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_id', models.IntegerField()),
                ('producto_id', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio', models.PositiveBigIntegerField(default=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
