# Generated by Django 4.2.7 on 2023-11-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrdenItem',
        ),
    ]
