# Generated by Django 4.2.7 on 2023-11-08 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cliente_operador_rename_numero_orden_numero_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='operador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.operador'),
        ),
    ]
